/**
  科目状态
  */
export enum AccountStatusEnum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
}
/**
  科目类型
  */
export enum AccountTypeEnum {
  ASSET = 'ASSET',
  EQUITY = 'EQUITY',
  EXPENSE = 'EXPENSE',
  LIABILITY = 'LIABILITY',
  REVENUE = 'REVENUE',
}
/**
  会计软件授权状态枚举
  */
export enum AccountingAuthStatusEnum {
  AUTHED = 'AUTHED',
  CANCELED = 'CANCELED',
  INIT = 'INIT',
}
/**
  会计软件授权类型
  */
export enum AccountingAuthTypeEnum {
  ADD_ORG = 'ADD_ORG',
  SIGN_IN = 'SIGN_IN',
  SIGN_UP = 'SIGN_UP',
}
/**
  会计软件断连原因
  */
export enum AccountingDisconnectReasonEnum {
  ACCOUNTING_RESPONSE_AUTH_FAILED = 'ACCOUNTING_RESPONSE_AUTH_FAILED',
  USER_DISCONNECT_IN_PINVO = 'USER_DISCONNECT_IN_PINVO',
}
/**
  展示报表类型
  */
export enum AccountingReportShowTypeEnum {
  TOP_COST_OF_SALES_SUPPLIERS = 'TOP_COST_OF_SALES_SUPPLIERS',
  TOP_REVENUE_CUSTOMERS = 'TOP_REVENUE_CUSTOMERS',
}
/**
  会计软件枚举
  */
export enum AccountingSoftwareEnum {
  QB = 'QB',
  SAGE = 'SAGE',
  XERO = 'XERO',
}
/**
  附件关联对象类型
  */
export enum AttachmentTargetTypeEnum {
  CHASING_RECORD = 'CHASING_RECORD',
  GENERAL_QUESTION = 'GENERAL_QUESTION',
  VOUCHER = 'VOUCHER',
}
/**
  附件上传方式
  */
export enum AttachmentUploadMethodEnum {
  EMAIL = 'EMAIL',
  MANUAL = 'MANUAL',
  PINVO_IO_SYNC = 'PINVO_IO_SYNC',
}
/**
  附件上传场景
  */
export enum AttachmentUploadSceneEnum {
  APPLY_CHASING_UPLOAD_ATTACHMENT = 'APPLY_CHASING_UPLOAD_ATTACHMENT',
  BKP_UPLOAD_ATTACHMENTS_FOR_GENERAL_QUESTION = 'BKP_UPLOAD_ATTACHMENTS_FOR_GENERAL_QUESTION',
  CLIENT_UPLOAD_DOCUMENTS = 'CLIENT_UPLOAD_DOCUMENTS',
  CLIENT_UPLOAD_DOCUMENT_AND_MATCH_STATEMENT_LINE = 'CLIENT_UPLOAD_DOCUMENT_AND_MATCH_STATEMENT_LINE',
  EMAIL_ATTACHMENT = 'EMAIL_ATTACHMENT',
  PINVO_IO_SYNC = 'PINVO_IO_SYNC',
  REPLY_CHASING_UPLOAD_ATTACHMENT = 'REPLY_CHASING_UPLOAD_ATTACHMENT',
}
/**
  银行流水科目来源
  */
export enum BankStatementAccountSourceEnum {
  FUND_DESCRIPTION = 'FUND_DESCRIPTION',
  NONE = 'NONE',
  ORG_CONFIRMED_VOUCHERS = 'ORG_CONFIRMED_VOUCHERS',
  SYSTEM_CERTAIN_RECON_VOUCHERS = 'SYSTEM_CERTAIN_RECON_VOUCHERS',
  SYSTEM_UNCERTAIN_RECON_VOUCHERS = 'SYSTEM_UNCERTAIN_RECON_VOUCHERS',
}
/**
  银行流水chasing状态
  */
export enum BankStatementLineChasingShowStatusEnum {
  CHASING = 'CHASING',
  COMPLETED = 'COMPLETED',
  NO_NEED_TO_CHASE = 'NO_NEED_TO_CHASE',
  TO_CHASE = 'TO_CHASE',
}
/**
  系统匹配到已有对手方的匹配方式
  */
export enum BankStatementLineContactMatchResultEnum {
  MATCH_CONTACT_ACCOUNT_NO = 'MATCH_CONTACT_ACCOUNT_NO',
  MATCH_CONTACT_BANK_ACCOUNT_NAME = 'MATCH_CONTACT_BANK_ACCOUNT_NAME',
  MATCH_CONTACT_NAME = 'MATCH_CONTACT_NAME',
  MATCH_CONTACT_PERSON_EMAIL = 'MATCH_CONTACT_PERSON_EMAIL',
  MATCH_CONTACT_PERSON_FIRST_NAME = 'MATCH_CONTACT_PERSON_FIRST_NAME',
  MATCH_CONTACT_PERSON_FULL_NAME = 'MATCH_CONTACT_PERSON_FULL_NAME',
  MATCH_CONTACT_PERSON_LAST_NAME = 'MATCH_CONTACT_PERSON_LAST_NAME',
  NO_MATCH_CONTACT = 'NO_MATCH_CONTACT',
  SIMILAR_STATEMENT_LINE_MATCH_CONTACT = 'SIMILAR_STATEMENT_LINE_MATCH_CONTACT',
  STATEMENT_LINE_NO_COUNTER_PARTY_NAME_OR_ACCOUNT_NO = 'STATEMENT_LINE_NO_COUNTER_PARTY_NAME_OR_ACCOUNT_NO',
}
/**
  银行流水展示状态
  */
export enum BankStatementLineShowStatusEnum {
  CERTAIN_RECON_SUCCESS = 'CERTAIN_RECON_SUCCESS',
  ORG_CONFIRMED = 'ORG_CONFIRMED',
  ORG_DENIED = 'ORG_DENIED',
  PRE_PROCESSING = 'PRE_PROCESSING',
  RECONCILING = 'RECONCILING',
  UNCERTAIN_RECON_FAILED = 'UNCERTAIN_RECON_FAILED',
  UNCERTAIN_RECON_SUCCESS = 'UNCERTAIN_RECON_SUCCESS',
  VOUCHER_PRE_PROCESSING = 'VOUCHER_PRE_PROCESSING',
}
/**
  记账频率
  */
export enum BookkeepingFrequencyEnum {
  BI_WEEKLY = 'BI_WEEKLY',
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
}
/**
  面向客户的记账进度状态
  */
export enum BookkeepingProgressToClientStatusEnum {
  CHASING_CLIENT = 'CHASING_CLIENT',
  CONFIRMED = 'CONFIRMED',
  HISTORICAL_DATA = 'HISTORICAL_DATA',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_START_YET = 'NOT_START_YET',
}
/**
  BILL/INVOICE业务凭证状态
  */
export enum BusinessVoucherStatusEnum {
  CANCELED = 'CANCELED',
  DELETED = 'DELETED',
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  UNKNOWN = 'UNKNOWN',
}
/**
  chasing问题类型
  */
export enum ChasingQuestionTypeEnum {
  BANK_STATEMENT_LINE_PERSONAL_OR_BUSINESS = 'BANK_STATEMENT_LINE_PERSONAL_OR_BUSINESS',
  OPEN_QUESTION = 'OPEN_QUESTION',
}
/**
  chasing角色类型
  */
export enum ChasingRoleTypeEnum {
  BOOKKEEPER = 'BOOKKEEPER',
  CLIENT = 'CLIENT',
}
/**
  chasing状态
  */
export enum ChasingStatusEnum {
  CANCELLED = 'CANCELLED',
  CHASING = 'CHASING',
  COMPLETED = 'COMPLETED',
  INIT = 'INIT',
  REPLIED = 'REPLIED',
}
/**
  chasing目标类型
  */
export enum ChasingTargetTypeEnum {
  BANK_STATEMENT_LINE = 'BANK_STATEMENT_LINE',
  GENERAL_QUESTION = 'GENERAL_QUESTION',
  VOUCHER = 'VOUCHER',
}
/**
  chasing类型
  */
export enum ChasingTypeEnum {
  CHASING_CONTEXT = 'CHASING_CONTEXT',
  CHASING_VOUCHER = 'CHASING_VOUCHER',
}
/**
  通讯录装填
  */
export enum ContactStatusEnum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  UNKNOWN = 'UNKNOWN',
}
/**
  币种
  */
export enum CurrencyEnum {
  AUD = 'AUD',
  BGN = 'BGN',
  BRL = 'BRL',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  CZK = 'CZK',
  DKK = 'DKK',
  EUR = 'EUR',
  GBP = 'GBP',
  HKD = 'HKD',
  HRK = 'HRK',
  HUF = 'HUF',
  IDR = 'IDR',
  ILS = 'ILS',
  INR = 'INR',
  ISK = 'ISK',
  JPY = 'JPY',
  KRW = 'KRW',
  MXN = 'MXN',
  MYR = 'MYR',
  NOK = 'NOK',
  NZD = 'NZD',
  PHP = 'PHP',
  PLN = 'PLN',
  RON = 'RON',
  RUB = 'RUB',
  SEK = 'SEK',
  SGD = 'SGD',
  THB = 'THB',
  TRY = 'TRY',
  USD = 'USD',
  ZAR = 'ZAR',
}
/**
  凭证文档类型
  */
export enum DocumentTypeEnum {
  BANK_STATEMENT = 'BANK_STATEMENT',
  BILL = 'BILL',
  INVOICE = 'INVOICE',
  PAYSLIP = 'PAYSLIP',
  RECEIPT = 'RECEIPT',
  UNKNOWN = 'UNKNOWN',
}
/**
  资金方向
  */
export enum FundDirectionEnum {
  RECEIVE = 'RECEIVE',
  SPEND = 'SPEND',
}
/**
  资金凭证状态
  */
export enum FundVoucherStatusEnum {
  CANCELED = 'CANCELED',
  DELETED = 'DELETED',
  NORMAL = 'NORMAL',
}
/**
  HTTP内容类型枚举
  */
export enum HttpContentTypeEnum {
  AIFF = 'AIFF',
  ASP = 'ASP',
  AUDIO_BASIC = 'AUDIO_BASIC',
  AUDIO_MPEG = 'AUDIO_MPEG',
  AVI = 'AVI',
  BASIC = 'BASIC',
  BMP = 'BMP',
  CSS = 'CSS',
  CSV = 'CSV',
  FAX = 'FAX',
  GIF = 'GIF',
  GZIP = 'GZIP',
  HEIC = 'HEIC',
  HEIF = 'HEIF',
  HTML = 'HTML',
  IVF = 'IVF',
  JPEG = 'JPEG',
  MID = 'MID',
  MOV = 'MOV',
  MP1 = 'MP1',
  MP2 = 'MP2',
  MP3 = 'MP3',
  MP4 = 'MP4',
  MPEG4 = 'MPEG4',
  MPEGURL = 'MPEGURL',
  MSWORD = 'MSWORD',
  PDF = 'PDF',
  PNETVUE = 'PNETVUE',
  PNG = 'PNG',
  RN_MPEG = 'RN_MPEG',
  SCPLS = 'SCPLS',
  TIFF = 'TIFF',
  TXT = 'TXT',
  VIDEO_MPEG = 'VIDEO_MPEG',
  VND_APPLE_NUMBERS = 'VND_APPLE_NUMBERS',
  VND_MS_EXCEL = 'VND_MS_EXCEL',
  VND_MS_POWERPOINT = 'VND_MS_POWERPOINT',
  VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION = 'VND_OPENXMLFORMATS_OFFICEDOCUMENT_PRESENTATIONML_PRESENTATION',
  VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET = 'VND_OPENXMLFORMATS_OFFICEDOCUMENT_SPREADSHEETML_SHEET',
  VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT = 'VND_OPENXMLFORMATS_OFFICEDOCUMENT_WORDPROCESSINGML_DOCUMENT',
  VND_RAR = 'VND_RAR',
  VND_RN_REALMEDIA_VBR = 'VND_RN_REALMEDIA_VBR',
  WAV = 'WAV',
  WEBP = 'WEBP',
  XML = 'XML',
  X_7Z_COMPRESSED = 'X_7Z_COMPRESSED',
  X_BMP = 'X_BMP',
  X_BZIP = 'X_BZIP',
  X_BZIP2 = 'X_BZIP2',
  X_ICO = 'X_ICO',
  X_ICON = 'X_ICON',
  X_IMG = 'X_IMG',
  X_IWORK_NUMBERS_SFFNUMBERS = 'X_IWORK_NUMBERS_SFFNUMBERS',
  X_JPG = 'X_JPG',
  X_LA_LMS = 'X_LA_LMS',
  X_LIQUID_FILE = 'X_LIQUID_FILE',
  X_LIQUID_SECURE = 'X_LIQUID_SECURE',
  X_M4A = 'X_M4A',
  X_MEI_AAC = 'X_MEI_AAC',
  X_MPEG = 'X_MPEG',
  X_MPG = 'X_MPG',
  X_MS_ASF = 'X_MS_ASF',
  X_MS_BMP = 'X_MS_BMP',
  X_MS_WAX = 'X_MS_WAX',
  X_MS_WM = 'X_MS_WM',
  X_MS_WMA = 'X_MS_WMA',
  X_MS_WMV = 'X_MS_WMV',
  X_MS_WMX = 'X_MS_WMX',
  X_MS_WVX = 'X_MS_WVX',
  X_PIC = 'X_PIC',
  X_PNG = 'X_PNG',
  X_PPT = 'X_PPT',
  X_SGI_MOVIE = 'X_SGI_MOVIE',
  X_TAR = 'X_TAR',
  X_XLS = 'X_XLS',
  X_ZIP_COMPRESSED = 'X_ZIP_COMPRESSED',
  ZIP = 'ZIP',
}
/**
  item的金额类型
  */
export enum ItemAmountTypeEnum {
  EXCLUSIVE = 'EXCLUSIVE',
  INCLUSIVE = 'INCLUSIVE',
  NO_TAX = 'NO_TAX',
}
/**
  人工对账记录状态
  */
export enum ManualReconRecordStatusEnum {
  CONFIRMED = 'CONFIRMED',
  INIT = 'INIT',
  SYNCED = 'SYNCED',
  SYNCING = 'SYNCING',
}
/**
  媒体类型
  */
export enum MediumTypeEnum {
  AUDIO = 'AUDIO',
  FILE = 'FILE',
  IMAGE = 'IMAGE',
  TEXT = 'TEXT',
  VIDEO = 'VIDEO',
}
/**
  undefined
  */
export enum undefined {
  BANK_STATEMENT = 'BANK_STATEMENT',
  INVOICE = 'INVOICE',
  PAYSLIP = 'PAYSLIP',
  RECEIPT = 'RECEIPT',
  UNKNOWN = 'UNKNOWN',
}
/**
  OCR凭证状态
  */
export enum OcrVoucherStatusEnum {
  CANCELED = 'CANCELED',
  CONFIRMED = 'CONFIRMED',
  DELETED = 'DELETED',
  INIT = 'INIT',
  NORMAL = 'NORMAL',
}
/**
  OCR识别单据类型
  */
export enum OcrBusinessVoucherTypeEnum {
  BANK_STATEMENT = 'BANK_STATEMENT',
  INVOICE = 'INVOICE',
  PAYSLIP = 'PAYSLIP',
  RECEIPT = 'RECEIPT',
  UNKNOWN = 'UNKNOWN',
}
/**
  OB支付授权状态
  */
export enum OpenBankingPaymentAuthStatusEnum {
  AUTHORIZED = 'AUTHORIZED',
  AWAITING_AUTHORIZATION = 'AWAITING_AUTHORIZATION',
  CONSUMED = 'CONSUMED',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  REVOKED = 'REVOKED',
}
/**
  OB支付ISO状态
  */
export enum OpenBankingPaymentISOStatusEnum {
  ACCC = 'ACCC',
  ACCP = 'ACCP',
  ACFC = 'ACFC',
  ACSC = 'ACSC',
  ACSP = 'ACSP',
  ACTC = 'ACTC',
  ACWC = 'ACWC',
  ACWP = 'ACWP',
  CANC = 'CANC',
  PART = 'PART',
  PATC = 'PATC',
  PDNG = 'PDNG',
  RCVD = 'RCVD',
  RJCT = 'RJCT',
}
/**
  OB支付状态
  */
export enum OpenBankingPaymentStatusEnum {
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
}
/**
  客户否定对账的原因枚举
  */
export enum OrgReconDeniedReasonEnum {
  BANK_STATEMENT_CAN_NOT_MATCH_FUND_DESC = 'BANK_STATEMENT_CAN_NOT_MATCH_FUND_DESC',
  VOUCHER_MATCH_OTHER_STATEMENT_LINE = 'VOUCHER_MATCH_OTHER_STATEMENT_LINE',
  VOUCHER_UPLOADED_WAIT_RECON = 'VOUCHER_UPLOADED_WAIT_RECON',
}
/**
  组织任务完成状态枚举
  */
export enum OrgTaskStatusEnum {
  DELETE = 'DELETE',
  DONE = 'DONE',
  INIT = 'INIT',
}
/**
  组织任务类型
  */
export enum OrgTaskTypeEnum {
  AUTHORIZE_CLIENT_ACCESS_XERO = 'AUTHORIZE_CLIENT_ACCESS_XERO',
  CHECK_AND_SUBMIT_CIS_AUTH_CODE = 'CHECK_AND_SUBMIT_CIS_AUTH_CODE',
  CHECK_AND_SUBMIT_COMPANIES_HOUSE_AUTH_CODE = 'CHECK_AND_SUBMIT_COMPANIES_HOUSE_AUTH_CODE',
  CHECK_AND_SUBMIT_CORPORATE_TAX_AUTH_CODE = 'CHECK_AND_SUBMIT_CORPORATE_TAX_AUTH_CODE',
  CHECK_AND_SUBMIT_PAYE_AUTH_CODE = 'CHECK_AND_SUBMIT_PAYE_AUTH_CODE',
  CHECK_AND_SUBMIT_UTR_NUMBER = 'CHECK_AND_SUBMIT_UTR_NUMBER',
  CHECK_AND_SUBMIT_VAT_AUTH_CODE = 'CHECK_AND_SUBMIT_VAT_AUTH_CODE',
  DOCUMENTS_REQUEST = 'DOCUMENTS_REQUEST',
  GENERAL_QUESTION_ANSWERING = 'GENERAL_QUESTION_ANSWERING',
  TRANSACTION_CONTEXT_CONFIRM = 'TRANSACTION_CONTEXT_CONFIRM',
  UPLOAD_BANK_STATEMENT_LINES_MANUALLY = 'UPLOAD_BANK_STATEMENT_LINES_MANUALLY',
  XERO_BIND_BANK_ACCOUNT = 'XERO_BIND_BANK_ACCOUNT',
}
/**
  组织类型枚举
  */
export enum OrgTypeEnum {
  COMPANY = 'COMPANY',
  PERSON = 'PERSON',
}
/**
  支付类型
  */
export enum PaymentTypeEnum {
  BULK_PAYMENT = 'BULK_PAYMENT',
  DIRECT_DEBIT = 'DIRECT_DEBIT',
  DOMESTIC_RECURRING_PAYMENT = 'DOMESTIC_RECURRING_PAYMENT',
  DOMESTIC_SCHEDULED_PAYMENT = 'DOMESTIC_SCHEDULED_PAYMENT',
  DOMESTIC_SINGLE_PAYMENT = 'DOMESTIC_SINGLE_PAYMENT',
}
/**
  Pinvo服务包
  */
export enum PinvoServicePackageEnum {
  BESPOKE = 'BESPOKE',
  GROWTH = 'GROWTH',
  LITE = 'LITE',
  MINI = 'MINI',
  PRO = 'PRO',
  PRO_MAX = 'PRO_MAX',
  STARTER = 'STARTER',
}
/**
  对账记录大类的对账状态
  */
export enum ReconRecordCategoryShowStatusEnum {
  ASKING_CLIENT = 'ASKING_CLIENT',
  DONE = 'DONE',
  EXPORTING = 'EXPORTING',
  PROCESSING = 'PROCESSING',
  TO_REVIEW = 'TO_REVIEW',
}
/**
  对账记录显示的对账状态
  */
export enum ReconRecordShowStatusEnum {
  BANK_STATEMENT_PRE_PROCESSING = 'BANK_STATEMENT_PRE_PROCESSING',
  RECONCILING = 'RECONCILING',
  VOUCHER_PRE_PROCESSING = 'VOUCHER_PRE_PROCESSING',
}
/**
  对账记录状态
  */
export enum ReconRecordStatusEnum {
  CERTAIN_RECON_FAILED = 'CERTAIN_RECON_FAILED',
  CERTAIN_RECON_SUCCESS = 'CERTAIN_RECON_SUCCESS',
  INIT = 'INIT',
  ORG_CONFIRMED = 'ORG_CONFIRMED',
  ORG_DENIED = 'ORG_DENIED',
  UNCERTAIN_RECON_FAILED = 'UNCERTAIN_RECON_FAILED',
  UNCERTAIN_RECON_SUCCESS = 'UNCERTAIN_RECON_SUCCESS',
}
/**
  对账成功的原因
  */
export enum ReconResultEnum {
  BANK_FUND = 'BANK_FUND',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  ONLY_MATCH_VOUCHER_RECONCILED_IN_ACCOUNTING = 'ONLY_MATCH_VOUCHER_RECONCILED_IN_ACCOUNTING',
  RECON_WITH_VOUCHERS = 'RECON_WITH_VOUCHERS',
}
/**
  可读错误码
  */
export enum PaiResultCode {
  ACCOUNTING_VOUCHER_ID_IS_NOT_BLANK = 'ACCOUNTING_VOUCHER_ID_IS_NOT_BLANK',
  PAI_ACCOUNTING_ALLOW_ACCESS_IS_NULL = 'PAI_ACCOUNTING_ALLOW_ACCESS_IS_NULL',
  PAI_ACCOUNTING_AUTHED_RECORD_ALREADY_EXISTS = 'PAI_ACCOUNTING_AUTHED_RECORD_ALREADY_EXISTS',
  PAI_ACCOUNTING_AUTH_CODE_IS_BLANK = 'PAI_ACCOUNTING_AUTH_CODE_IS_BLANK',
  PAI_ACCOUNTING_AUTH_CONFIRM_IS_NULL = 'PAI_ACCOUNTING_AUTH_CONFIRM_IS_NULL',
  PAI_ACCOUNTING_AUTH_RECORD_NOT_EXIST = 'PAI_ACCOUNTING_AUTH_RECORD_NOT_EXIST',
  PAI_ACCOUNTING_AUTH_RECORD_STATUS_NOT_AUTHED = 'PAI_ACCOUNTING_AUTH_RECORD_STATUS_NOT_AUTHED',
  PAI_ACCOUNTING_AUTH_RECORD_STATUS_TURN_EXCEPTION = 'PAI_ACCOUNTING_AUTH_RECORD_STATUS_TURN_EXCEPTION',
  PAI_ACCOUNTING_AUTH_TYPE_IS_NULL = 'PAI_ACCOUNTING_AUTH_TYPE_IS_NULL',
  PAI_ACCOUNTING_DATA_ILLEGAL = 'PAI_ACCOUNTING_DATA_ILLEGAL',
  PAI_ACCOUNTING_PLAN_NOT_SUPPORT_INVOICES = 'PAI_ACCOUNTING_PLAN_NOT_SUPPORT_INVOICES',
  PAI_ACCOUNTING_REPORT_SHOW_TYPE_ILLEGAL = 'PAI_ACCOUNTING_REPORT_SHOW_TYPE_ILLEGAL',
  PAI_ACCOUNTING_SOFTWARE_ILLEGAL = 'PAI_ACCOUNTING_SOFTWARE_ILLEGAL',
  PAI_ACCOUNT_ID_IS_BLANK = 'PAI_ACCOUNT_ID_IS_BLANK',
  PAI_ACCOUNT_NOT_BANK_ACCOUNT_TYPE = 'PAI_ACCOUNT_NOT_BANK_ACCOUNT_TYPE',
  PAI_ACCOUNT_NOT_EXIST = 'PAI_ACCOUNT_NOT_EXIST',
  PAI_ACCOUNT_PREDICT_REQUEST_IS_NULL = 'PAI_ACCOUNT_PREDICT_REQUEST_IS_NULL',
  PAI_ACCOUNT_STATUS_NOT_ACTIVE = 'PAI_ACCOUNT_STATUS_NOT_ACTIVE',
  PAI_ACCOUNT_TYPE_ILLEGAL = 'PAI_ACCOUNT_TYPE_ILLEGAL',
  PAI_AES_KEY_ID_IS_BLANK = 'PAI_AES_KEY_ID_IS_BLANK',
  PAI_AMOUNT_IS_NULL = 'PAI_AMOUNT_IS_NULL',
  PAI_ATTACHMENT_UPLOAD_METHOD_IS_BLANK = 'PAI_ATTACHMENT_UPLOAD_METHOD_IS_BLANK',
  PAI_ATTACHMENT_UPLOAD_METHOD_IS_INVALID = 'PAI_ATTACHMENT_UPLOAD_METHOD_IS_INVALID',
  PAI_ATTACHMENT_UPLOAD_SCENE_IS_BLANK = 'PAI_ATTACHMENT_UPLOAD_SCENE_IS_BLANK',
  PAI_ATTACHMENT_UPLOAD_SCENE_IS_INVALID = 'PAI_ATTACHMENT_UPLOAD_SCENE_IS_INVALID',
  PAI_AUTH_CODE_INCONSISTENCY = 'PAI_AUTH_CODE_INCONSISTENCY',
  PAI_AUTH_CODE_IS_BLANK = 'PAI_AUTH_CODE_IS_BLANK',
  PAI_BANK_ACCOUNT_ID_IS_BLANK = 'PAI_BANK_ACCOUNT_ID_IS_BLANK',
  PAI_BANK_STATEMENT_LINE_DISCUSS_IS_BLANK = 'PAI_BANK_STATEMENT_LINE_DISCUSS_IS_BLANK',
  PAI_BANK_STATEMENT_LINE_ID_IS_NULL = 'PAI_BANK_STATEMENT_LINE_ID_IS_NULL',
  PAI_BANK_STATEMENT_LINE_ID_LIST_IS_EMPTY = 'PAI_BANK_STATEMENT_LINE_ID_LIST_IS_EMPTY',
  PAI_BANK_STATEMENT_LINE_RECON_STATUS_IS_INVALID = 'PAI_BANK_STATEMENT_LINE_RECON_STATUS_IS_INVALID',
  PAI_BASE_CURRENCY_IS_NULL = 'PAI_BASE_CURRENCY_IS_NULL',
  PAI_BUSINESS_VOUCHER_PAYMENT_RECORD_NOT_EXIST = 'PAI_BUSINESS_VOUCHER_PAYMENT_RECORD_NOT_EXIST',
  PAI_CALL_AUTO_BKP_COMPLETION_ERROR = 'PAI_CALL_AUTO_BKP_COMPLETION_ERROR',
  PAI_CALL_GOOGLE_ERROR = 'PAI_CALL_GOOGLE_ERROR',
  PAI_CALL_NUXT_BKP_COMPLETION_ERROR = 'PAI_CALL_NUXT_BKP_COMPLETION_ERROR',
  PAI_CALL_PINVO_ERROR = 'PAI_CALL_PINVO_ERROR',
  PAI_CHASING_FAILED = 'PAI_CHASING_FAILED',
  PAI_CHASING_QUESTION_IS_NULL = 'PAI_CHASING_QUESTION_IS_NULL',
  PAI_CHASING_QUESTION_TYPE_IS_ILLEGAL = 'PAI_CHASING_QUESTION_TYPE_IS_ILLEGAL',
  PAI_CHASING_QUESTION_TYPE_IS_NULL = 'PAI_CHASING_QUESTION_TYPE_IS_NULL',
  PAI_CHASING_RECORD_ID_IS_BLANK = 'PAI_CHASING_RECORD_ID_IS_BLANK',
  PAI_CHASING_RECORD_NOT_EXIST = 'PAI_CHASING_RECORD_NOT_EXIST',
  PAI_CHASING_RECORD_STATUS_ILLEGAL = 'PAI_CHASING_RECORD_STATUS_ILLEGAL',
  PAI_CHASING_RECORD_TARGET_TYPE_ILLEGAL = 'PAI_CHASING_RECORD_TARGET_TYPE_ILLEGAL',
  PAI_CHASING_STATUS_IS_NULL = 'PAI_CHASING_STATUS_IS_NULL',
  PAI_CHASING_TARGET_TYPE_IS_NULL = 'PAI_CHASING_TARGET_TYPE_IS_NULL',
  PAI_CHASING_TYPE_IS_NULL = 'PAI_CHASING_TYPE_IS_NULL',
  PAI_CHECK_STATISTIC_DATA_FAIL = 'PAI_CHECK_STATISTIC_DATA_FAIL',
  PAI_CLIENT_ID_IS_BLANK = 'PAI_CLIENT_ID_IS_BLANK',
  PAI_CLIENT_RSA_PUBLIC_KEY_IS_BLANK = 'PAI_CLIENT_RSA_PUBLIC_KEY_IS_BLANK',
  PAI_COMPANY_HOUSE_NAME_NOT_MATCH = 'PAI_COMPANY_HOUSE_NAME_NOT_MATCH',
  PAI_COMPANY_HOUSE_SEARCH_NO_RESULT = 'PAI_COMPANY_HOUSE_SEARCH_NO_RESULT',
  PAI_CONTACT_CREATE_REQUEST_NULL = 'PAI_CONTACT_CREATE_REQUEST_NULL',
  PAI_CONTACT_ID_IS_BLANK = 'PAI_CONTACT_ID_IS_BLANK',
  PAI_CONTACT_IS_NULL = 'PAI_CONTACT_IS_NULL',
  PAI_CONTACT_MODIFY_REQUEST_NULL = 'PAI_CONTACT_MODIFY_REQUEST_NULL',
  PAI_CONTACT_NAME_IS_BLANK = 'PAI_CONTACT_NAME_IS_BLANK',
  PAI_CONTACT_NAME_NOT_EMPTY = 'PAI_CONTACT_NAME_NOT_EMPTY',
  PAI_CONTACT_NOT_EXIST = 'PAI_CONTACT_NOT_EXIST',
  PAI_CONTACT_PAGE_QUERY_REQUEST_NULL = 'PAI_CONTACT_PAGE_QUERY_REQUEST_NULL',
  PAI_CURRENCY_EXCHANGE_ERROR = 'PAI_CURRENCY_EXCHANGE_ERROR',
  PAI_CURRENCY_ILLEGAL = 'PAI_CURRENCY_ILLEGAL',
  PAI_DATE_IS_BLANK = 'PAI_DATE_IS_BLANK',
  PAI_DESCRIPTION_IS_BLANK = 'PAI_DESCRIPTION_IS_BLANK',
  PAI_DISCONNECT_XERO_ORG_EXCEPTION = 'PAI_DISCONNECT_XERO_ORG_EXCEPTION',
  PAI_EMAIL_DELIVER_RECORD_NOT_EXIST = 'PAI_EMAIL_DELIVER_RECORD_NOT_EXIST',
  PAI_EMAIL_FORMAT_ILLEGAL = 'PAI_EMAIL_FORMAT_ILLEGAL',
  PAI_EMAIL_IS_BLANK = 'PAI_EMAIL_IS_BLANK',
  PAI_EMAIL_TEMPLATE_NOT_EXIST = 'PAI_EMAIL_TEMPLATE_NOT_EXIST',
  PAI_ENCRYPT_CONFIG_RECORD_NOT_EXIST = 'PAI_ENCRYPT_CONFIG_RECORD_NOT_EXIST',
  PAI_ENDING_DATE_ILLEGAL = 'PAI_ENDING_DATE_ILLEGAL',
  PAI_FETCH_MEDIUM_UPLOAD_URL_PARAM_ILLEGAL = 'PAI_FETCH_MEDIUM_UPLOAD_URL_PARAM_ILLEGAL',
  PAI_FUND_DATE_ILLEGAL = 'PAI_FUND_DATE_ILLEGAL',
  PAI_FUND_DESCRIPTION_ID_IS_BLANK = 'PAI_FUND_DESCRIPTION_ID_IS_BLANK',
  PAI_FUND_DIRECTION_IS_NULL = 'PAI_FUND_DIRECTION_IS_NULL',
  PAI_FUND_DIRECTION_UNEQUAL = 'PAI_FUND_DIRECTION_UNEQUAL',
  PAI_FUND_MAIN_DESCRIPTION_IS_BLANK = 'PAI_FUND_MAIN_DESCRIPTION_IS_BLANK',
  PAI_FUND_SUB_DESCRIPTIONS_IS_EMPTY = 'PAI_FUND_SUB_DESCRIPTIONS_IS_EMPTY',
  PAI_FUND_SUB_DESCRIPTION_IS_BLANK = 'PAI_FUND_SUB_DESCRIPTION_IS_BLANK',
  PAI_FUND_VOUCHER_ACCOUNTING_RECONCILED_IS_NULL = 'PAI_FUND_VOUCHER_ACCOUNTING_RECONCILED_IS_NULL',
  PAI_FUND_VOUCHER_BANK_ACCOUNT_ID_IS_BLANK = 'PAI_FUND_VOUCHER_BANK_ACCOUNT_ID_IS_BLANK',
  PAI_GENERAL_QUESTION_IS_BLANK = 'PAI_GENERAL_QUESTION_IS_BLANK',
  PAI_GENERAL_QUESTION_NOT_EXIST = 'PAI_GENERAL_QUESTION_NOT_EXIST',
  PAI_GET_XERO_ORG_EXCEPTION = 'PAI_GET_XERO_ORG_EXCEPTION',
  PAI_GET_XERO_TOKEN_EXCEPTION = 'PAI_GET_XERO_TOKEN_EXCEPTION',
  PAI_GOOGLE_DRIVE_FOLDER_NOT_EXIST = 'PAI_GOOGLE_DRIVE_FOLDER_NOT_EXIST',
  PAI_GOOGLE_SHEETS_TEMPLATE_NOT_EXIST = 'PAI_GOOGLE_SHEETS_TEMPLATE_NOT_EXIST',
  PAI_ITEMS_IS_EMPTY = 'PAI_ITEMS_IS_EMPTY',
  PAI_ITEM_AMOUNT_ILLEGAL = 'PAI_ITEM_AMOUNT_ILLEGAL',
  PAI_ITEM_AMOUNT_TYPE_IS_NULL = 'PAI_ITEM_AMOUNT_TYPE_IS_NULL',
  PAI_ITEM_DESCRIPTION_IS_BLANK = 'PAI_ITEM_DESCRIPTION_IS_BLANK',
  PAI_ITEM_NOT_EXIST = 'PAI_ITEM_NOT_EXIST',
  PAI_ITEM_QUANTITY_ILLEGAL = 'PAI_ITEM_QUANTITY_ILLEGAL',
  PAI_ITEM_TAX_AMOUNT_ILLEGAL = 'PAI_ITEM_TAX_AMOUNT_ILLEGAL',
  PAI_ITEM_UNIT_AMOUNT_ILLEGAL = 'PAI_ITEM_UNIT_AMOUNT_ILLEGAL',
  PAI_LOGIN_ID_IS_BLANK = 'PAI_LOGIN_ID_IS_BLANK',
  PAI_LOGIN_ID_NOT_EXIST = 'PAI_LOGIN_ID_NOT_EXIST',
  PAI_LOGIN_OTP_IS_BLANK = 'PAI_LOGIN_OTP_IS_BLANK',
  PAI_LOGIN_PWD_IS_BLANK = 'PAI_LOGIN_PWD_IS_BLANK',
  PAI_MANUAL_CONFIRMED_VOUCHER_NOT_ALLOWED_TO_SYNC_DIRECTLY = 'PAI_MANUAL_CONFIRMED_VOUCHER_NOT_ALLOWED_TO_SYNC_DIRECTLY',
  PAI_MANUAL_RECON_RECORD_IS_NULL = 'PAI_MANUAL_RECON_RECORD_IS_NULL',
  PAI_MANUAL_RECON_RECORD_STATUS_ILLEGAL = 'PAI_MANUAL_RECON_RECORD_STATUS_ILLEGAL',
  PAI_MAX_INDEX_IS_NULL = 'PAI_MAX_INDEX_IS_NULL',
  PAI_MEDIUM_IDS_IS_NULL = 'PAI_MEDIUM_IDS_IS_NULL',
  PAI_MEDIUM_NOT_EXIST = 'PAI_MEDIUM_NOT_EXIST',
  PAI_MEDIUM_REGISTER_REQUEST_IS_NULL = 'PAI_MEDIUM_REGISTER_REQUEST_IS_NULL',
  PAI_MEDIUM_TYPE_IS_NOT_SUPPORT = 'PAI_MEDIUM_TYPE_IS_NOT_SUPPORT',
  PAI_MEDIUM_TYPE_IS_NULL = 'PAI_MEDIUM_TYPE_IS_NULL',
  PAI_MORE_THAN_ONE_BUSINESS_VOUCHER_PAYMENT_RECORD = 'PAI_MORE_THAN_ONE_BUSINESS_VOUCHER_PAYMENT_RECORD',
  PAI_MULTI_ITEM_VOUCHER_CANNOT_UPDATE_ACCOUNT_OR_TAX_RATE = 'PAI_MULTI_ITEM_VOUCHER_CANNOT_UPDATE_ACCOUNT_OR_TAX_RATE',
  PAI_NOTIFICATION_CONTENT_ASSEMBLER_NOT_EXIST = 'PAI_NOTIFICATION_CONTENT_ASSEMBLER_NOT_EXIST',
  PAI_NOTIFICATION_DELIVER_RECORD_ID_NOT_EXIST = 'PAI_NOTIFICATION_DELIVER_RECORD_ID_NOT_EXIST',
  PAI_ONBOARDING_CALL_AUDIO_URL_IS_BLANK = 'PAI_ONBOARDING_CALL_AUDIO_URL_IS_BLANK',
  PAI_ONBOARDING_CALL_AUDIO_URL_IS_INVALID = 'PAI_ONBOARDING_CALL_AUDIO_URL_IS_INVALID',
  PAI_ONLY_SUPPORT_UK_ORG = 'PAI_ONLY_SUPPORT_UK_ORG',
  PAI_ORG_ASSIGNED_EMAIL_STATUS_IS_NOT_NORMAL = 'PAI_ORG_ASSIGNED_EMAIL_STATUS_IS_NOT_NORMAL',
  PAI_ORG_ASSIGNED_EMAIL_USER_NAME_IS_BLANK = 'PAI_ORG_ASSIGNED_EMAIL_USER_NAME_IS_BLANK',
  PAI_ORG_CONFIRM_RECON_VOUCHER_DETAILS_IS_EMPTY = 'PAI_ORG_CONFIRM_RECON_VOUCHER_DETAILS_IS_EMPTY',
  PAI_ORG_HAS_INIT_OR_PRE_PROCESSING_BANK_STATEMENT_LINE = 'PAI_ORG_HAS_INIT_OR_PRE_PROCESSING_BANK_STATEMENT_LINE',
  PAI_ORG_HAS_INIT_RECON_RECORD = 'PAI_ORG_HAS_INIT_RECON_RECORD',
  PAI_ORG_HAS_NO_BOOKKEEPER = 'PAI_ORG_HAS_NO_BOOKKEEPER',
  PAI_ORG_ID_IS_BLANK = 'PAI_ORG_ID_IS_BLANK',
  PAI_ORG_ID_UNEQUAL = 'PAI_ORG_ID_UNEQUAL',
  PAI_ORG_NOT_CONNECT_TO_ACCOUNTING = 'PAI_ORG_NOT_CONNECT_TO_ACCOUNTING',
  PAI_ORG_NOT_EXIST = 'PAI_ORG_NOT_EXIST',
  PAI_ORG_TASK_DEST_STATUS_IS_BLANK = 'PAI_ORG_TASK_DEST_STATUS_IS_BLANK',
  PAI_ORG_TASK_DEST_STATUS_IS_INVALID = 'PAI_ORG_TASK_DEST_STATUS_IS_INVALID',
  PAI_ORG_TASK_ID_IS_BLANK = 'PAI_ORG_TASK_ID_IS_BLANK',
  PAI_ORG_TASK_NOT_EXIST = 'PAI_ORG_TASK_NOT_EXIST',
  PAI_PAGE_IS_NULL = 'PAI_PAGE_IS_NULL',
  PAI_PAGE_QUERY_UNMATCHED_VOUCHER_REQUEST_IS_NULL = 'PAI_PAGE_QUERY_UNMATCHED_VOUCHER_REQUEST_IS_NULL',
  PAI_PAGE_QUERY_VOUCHER_REQUEST_IS_NULL = 'PAI_PAGE_QUERY_VOUCHER_REQUEST_IS_NULL',
  PAI_PAGE_SIZE_IS_NULL = 'PAI_PAGE_SIZE_IS_NULL',
  PAI_PAYMENT_RECORD_AMOUNT_ILLEGAL = 'PAI_PAYMENT_RECORD_AMOUNT_ILLEGAL',
  PAI_PAYMENT_RECORD_DATE_IS_BLANK = 'PAI_PAYMENT_RECORD_DATE_IS_BLANK',
  PAI_PAYMENT_RECORD_ID_ILLEGAL = 'PAI_PAYMENT_RECORD_ID_ILLEGAL',
  PAI_PAYMENT_RECORD_PAYMENT_BANK_ILLEGAL = 'PAI_PAYMENT_RECORD_PAYMENT_BANK_ILLEGAL',
  PAI_PNG_FILE_PATH_IS_BLANK = 'PAI_PNG_FILE_PATH_IS_BLANK',
  PAI_PROFIT_AND_LOSS_REPORT_NOT_EXIST = 'PAI_PROFIT_AND_LOSS_REPORT_NOT_EXIST',
  PAI_QUERY_FILE_PARAM_ILLEGAL = 'PAI_QUERY_FILE_PARAM_ILLEGAL',
  PAI_QUERY_IMAGE_PARAM_ILLEGAL = 'PAI_QUERY_IMAGE_PARAM_ILLEGAL',
  PAI_QUESTION_NAME_IS_BLANK = 'PAI_QUESTION_NAME_IS_BLANK',
  PAI_RECON_AMOUNT_IS_NULL = 'PAI_RECON_AMOUNT_IS_NULL',
  PAI_RECON_AMOUNT_NOT_EQUAL = 'PAI_RECON_AMOUNT_NOT_EQUAL',
  PAI_RECON_DENIED_REASON_IS_NULL = 'PAI_RECON_DENIED_REASON_IS_NULL',
  PAI_RECON_FAILED = 'PAI_RECON_FAILED',
  PAI_RECON_RECORD_CATEGORY_SHOW_STATUS_IS_BLANK = 'PAI_RECON_RECORD_CATEGORY_SHOW_STATUS_IS_BLANK',
  PAI_RECON_RECORD_CATEGORY_SHOW_STATUS_IS_INVALID = 'PAI_RECON_RECORD_CATEGORY_SHOW_STATUS_IS_INVALID',
  PAI_RECON_RECORD_EXCEPTION = 'PAI_RECON_RECORD_EXCEPTION',
  PAI_RECON_RECORD_EXIST = 'PAI_RECON_RECORD_EXIST',
  PAI_RECON_RECORD_NOT_EXIST = 'PAI_RECON_RECORD_NOT_EXIST',
  PAI_RECON_RECORD_SHOW_STATUS_IS_BLANK = 'PAI_RECON_RECORD_SHOW_STATUS_IS_BLANK',
  PAI_RECON_RECORD_SHOW_STATUS_IS_INVALID = 'PAI_RECON_RECORD_SHOW_STATUS_IS_INVALID',
  PAI_RECON_RECORD_STATUS_ILLEGAL = 'PAI_RECON_RECORD_STATUS_ILLEGAL',
  PAI_RECON_RECORD_STATUS_IS_BLANK = 'PAI_RECON_RECORD_STATUS_IS_BLANK',
  PAI_RECON_RECORD_TYPE_IS_BLANK = 'PAI_RECON_RECORD_TYPE_IS_BLANK',
  PAI_RECON_RECORD_TYPE_IS_INVALID = 'PAI_RECON_RECORD_TYPE_IS_INVALID',
  PAI_RECON_VOUCHER_DETAIL_NOT_EXIST = 'PAI_RECON_VOUCHER_DETAIL_NOT_EXIST',
  PAI_RECORD_ID_IS_BLANK = 'PAI_RECORD_ID_IS_BLANK',
  PAI_REFRESH_TOKEN_FAILED = 'PAI_REFRESH_TOKEN_FAILED',
  PAI_REGISTER_FILE_PARAM_ILLEGAL = 'PAI_REGISTER_FILE_PARAM_ILLEGAL',
  PAI_REGISTER_IMAGE_PARAM_ILLEGAL = 'PAI_REGISTER_IMAGE_PARAM_ILLEGAL',
  PAI_REPLY_CHASING_REQUESTS_IS_EMPTY = 'PAI_REPLY_CHASING_REQUESTS_IS_EMPTY',
  PAI_REQUEST_ID_DUPLICATE = 'PAI_REQUEST_ID_DUPLICATE',
  PAI_REQUEST_ID_IS_BLANK = 'PAI_REQUEST_ID_IS_BLANK',
  PAI_REQUEST_IS_NULL = 'PAI_REQUEST_IS_NULL',
  PAI_SERVER_RSA_KEY_ID_IS_BLANK = 'PAI_SERVER_RSA_KEY_ID_IS_BLANK',
  PAI_STARTING_DATE_ILLEGAL = 'PAI_STARTING_DATE_ILLEGAL',
  PAI_STATEMENT_LINE_ID_IS_BLANK = 'PAI_STATEMENT_LINE_ID_IS_BLANK',
  PAI_STATEMENT_LINE_NOT_EXIST = 'PAI_STATEMENT_LINE_NOT_EXIST',
  PAI_STATEMENT_LINE_RECON_STATUS_ILLEGAL = 'PAI_STATEMENT_LINE_RECON_STATUS_ILLEGAL',
  PAI_STATE_IS_BLANK = 'PAI_STATE_IS_BLANK',
  PAI_STRIPE_CHECKOUT_SESSION_NOT_EXIST = 'PAI_STRIPE_CHECKOUT_SESSION_NOT_EXIST',
  PAI_STRIPE_PAYMENT_METHOD_ID_IS_BLANK = 'PAI_STRIPE_PAYMENT_METHOD_ID_IS_BLANK',
  PAI_STRIPE_PAYMENT_METHOD_NOT_EXIST = 'PAI_STRIPE_PAYMENT_METHOD_NOT_EXIST',
  PAI_SWITCH_SYNC_IS_NULL = 'PAI_SWITCH_SYNC_IS_NULL',
  PAI_SYNC_ATTACHMENT_TO_XERO_EXCEPTION = 'PAI_SYNC_ATTACHMENT_TO_XERO_EXCEPTION',
  PAI_SYNC_BANK_TRANSACTION_TO_XERO_EXCEPTION = 'PAI_SYNC_BANK_TRANSACTION_TO_XERO_EXCEPTION',
  PAI_SYNC_CONTACT_TO_XERO_EXCEPTION = 'PAI_SYNC_CONTACT_TO_XERO_EXCEPTION',
  PAI_SYNC_DATA_TO_XERO_EXCEPTION = 'PAI_SYNC_DATA_TO_XERO_EXCEPTION',
  PAI_SYNC_INVOICE_TO_XERO_EXCEPTION = 'PAI_SYNC_INVOICE_TO_XERO_EXCEPTION',
  PAI_SYNC_PAYMENT_TO_XERO_EXCEPTION = 'PAI_SYNC_PAYMENT_TO_XERO_EXCEPTION',
  PAI_SYSTEM_PARAM_KEY_IS_BLANK = 'PAI_SYSTEM_PARAM_KEY_IS_BLANK',
  PAI_SYSTEM_PARAM_KEY_IS_INVALID = 'PAI_SYSTEM_PARAM_KEY_IS_INVALID',
  PAI_SYSTEM_PARAM_VALUE_IS_BLANK = 'PAI_SYSTEM_PARAM_VALUE_IS_BLANK',
  PAI_TAX_RATE_ID_IS_BLANK = 'PAI_TAX_RATE_ID_IS_BLANK',
  PAI_TAX_RATE_NOT_EXIST = 'PAI_TAX_RATE_NOT_EXIST',
  PAI_UNKNOWN_VAT_RATE = 'PAI_UNKNOWN_VAT_RATE',
  PAI_UNMATCHED_BANK_STATEMENT_LINES_PAGE_QUERY_REQUEST_IS_NULL = 'PAI_UNMATCHED_BANK_STATEMENT_LINES_PAGE_QUERY_REQUEST_IS_NULL',
  PAI_UNSUPPORTED_CURRENCY = 'PAI_UNSUPPORTED_CURRENCY',
  PAI_UPLOAD_MEDIUM_FAILED = 'PAI_UPLOAD_MEDIUM_FAILED',
  PAI_URL_IS_BLANK = 'PAI_URL_IS_BLANK',
  PAI_USER_DENIED_XERO_AUTH = 'PAI_USER_DENIED_XERO_AUTH',
  PAI_USER_EMAIL_NOT_BKP = 'PAI_USER_EMAIL_NOT_BKP',
  PAI_USER_ID_IS_BLANK = 'PAI_USER_ID_IS_BLANK',
  PAI_USER_LOGIN_PARAM_ILLEGAL = 'PAI_USER_LOGIN_PARAM_ILLEGAL',
  PAI_USER_LOGIN_PWD_ERROR = 'PAI_USER_LOGIN_PWD_ERROR',
  PAI_USER_LOGIN_PWD_ERROR_TIMES_REACH_UPPER_LIMIT = 'PAI_USER_LOGIN_PWD_ERROR_TIMES_REACH_UPPER_LIMIT',
  PAI_USER_LOGIN_STATUS_ILLEGAL = 'PAI_USER_LOGIN_STATUS_ILLEGAL',
  PAI_USER_NOT_EXIST = 'PAI_USER_NOT_EXIST',
  PAI_USER_NOT_REGISTER_EMAIL_PWD_LOGIN = 'PAI_USER_NOT_REGISTER_EMAIL_PWD_LOGIN',
  PAI_USER_NO_PERMISSION_OPERATE_ORG = 'PAI_USER_NO_PERMISSION_OPERATE_ORG',
  PAI_USER_ORG_ROLE_RELATION_NOT_EXIST = 'PAI_USER_ORG_ROLE_RELATION_NOT_EXIST',
  PAI_USER_ROLE_INVALID = 'PAI_USER_ROLE_INVALID',
  PAI_USER_ROLE_IS_BLANK = 'PAI_USER_ROLE_IS_BLANK',
  PAI_USER_ROLE_LIST_IS_EMPTY = 'PAI_USER_ROLE_LIST_IS_EMPTY',
  PAI_VOUCHER_AMOUNT_INCONSISTENCY = 'PAI_VOUCHER_AMOUNT_INCONSISTENCY',
  PAI_VOUCHER_AMOUNT_NOT_MATCH = 'PAI_VOUCHER_AMOUNT_NOT_MATCH',
  PAI_VOUCHER_CONTACT_ID_IS_BLANK = 'PAI_VOUCHER_CONTACT_ID_IS_BLANK',
  PAI_VOUCHER_DOCUMENT_TYPE_IS_BLANK = 'PAI_VOUCHER_DOCUMENT_TYPE_IS_BLANK',
  PAI_VOUCHER_DOCUMENT_TYPE_IS_INVALID = 'PAI_VOUCHER_DOCUMENT_TYPE_IS_INVALID',
  PAI_VOUCHER_DOC_TYPE_ILLEGAL = 'PAI_VOUCHER_DOC_TYPE_ILLEGAL',
  PAI_VOUCHER_DOC_TYPE_NOT_ACCOUNTING_VOUCHER_TYPE = 'PAI_VOUCHER_DOC_TYPE_NOT_ACCOUNTING_VOUCHER_TYPE',
  PAI_VOUCHER_DUE_DATE_IS_BLANK = 'PAI_VOUCHER_DUE_DATE_IS_BLANK',
  PAI_VOUCHER_IDS_IS_NULL = 'PAI_VOUCHER_IDS_IS_NULL',
  PAI_VOUCHER_ID_IS_BLANK = 'PAI_VOUCHER_ID_IS_BLANK',
  PAI_VOUCHER_INVALID_REQUEST_IS_NULL = 'PAI_VOUCHER_INVALID_REQUEST_IS_NULL',
  PAI_VOUCHER_ISSUE_DATE_IS_BLANK = 'PAI_VOUCHER_ISSUE_DATE_IS_BLANK',
  PAI_VOUCHER_MODIFY_REQUEST_IS_NULL = 'PAI_VOUCHER_MODIFY_REQUEST_IS_NULL',
  PAI_VOUCHER_NOT_EXIST = 'PAI_VOUCHER_NOT_EXIST',
  PAI_VOUCHER_NO_DUPLICATE = 'PAI_VOUCHER_NO_DUPLICATE',
  PAI_VOUCHER_NO_IS_BLANK = 'PAI_VOUCHER_NO_IS_BLANK',
  PAI_VOUCHER_NO_IS_DUPLICATE = 'PAI_VOUCHER_NO_IS_DUPLICATE',
  PAI_VOUCHER_QUERY_REQUEST_IS_NULL = 'PAI_VOUCHER_QUERY_REQUEST_IS_NULL',
  PAI_VOUCHER_RECON_STATUS_ILLEGAL = 'PAI_VOUCHER_RECON_STATUS_ILLEGAL',
  PAI_VOUCHER_SOURCE_ILLEGAL = 'PAI_VOUCHER_SOURCE_ILLEGAL',
  PAI_VOUCHER_SUB_TYPE_IS_NULL = 'PAI_VOUCHER_SUB_TYPE_IS_NULL',
  PAI_VOUCHER_SYNC_TO_ACCOUNTING_REASON_ILLEGAL = 'PAI_VOUCHER_SYNC_TO_ACCOUNTING_REASON_ILLEGAL',
  PAI_VOUCHER_SYNC_TO_ACCOUNTING_STATUS_ILLEGAL = 'PAI_VOUCHER_SYNC_TO_ACCOUNTING_STATUS_ILLEGAL',
  PAI_VOUCHER_TOTAL_AMOUNT_IS_NULL = 'PAI_VOUCHER_TOTAL_AMOUNT_IS_NULL',
  PAI_VOUCHER_TYPE_ILLEGAL = 'PAI_VOUCHER_TYPE_ILLEGAL',
  PAI_VOUCHER_TYPE_IS_NULL = 'PAI_VOUCHER_TYPE_IS_NULL',
  PAI_WEB_ELEMENT_GRAB_FAILED = 'PAI_WEB_ELEMENT_GRAB_FAILED',
  PAI_XERO_ACCOUNT_CREATE_FAILED = 'PAI_XERO_ACCOUNT_CREATE_FAILED',
  PAI_XERO_ACCOUNT_INCONSISTENCY = 'PAI_XERO_ACCOUNT_INCONSISTENCY',
  PAI_XERO_ACCOUNT_UPDATE_FAILED = 'PAI_XERO_ACCOUNT_UPDATE_FAILED',
  PAI_XERO_GET_DATA_EXCEPTION = 'PAI_XERO_GET_DATA_EXCEPTION',
  PAI_XERO_ORG_HAS_MORE_THAN_ONE_AUTHED_RECORD = 'PAI_XERO_ORG_HAS_MORE_THAN_ONE_AUTHED_RECORD',
  PAI_XERO_WEBHOOK_EVENT_ILLEGAL = 'PAI_XERO_WEBHOOK_EVENT_ILLEGAL',
  PAI_XERO_WEBHOOK_EVENT_IS_BLANK = 'PAI_XERO_WEBHOOK_EVENT_IS_BLANK',
  PAI_XERO_WEBHOOK_SIGNATURE_ILLEGAL = 'PAI_XERO_WEBHOOK_SIGNATURE_ILLEGAL',
  PAI_XERO_WEBHOOK_SIGNATURE_IS_BLANK = 'PAI_XERO_WEBHOOK_SIGNATURE_IS_BLANK',
  PAI_YAPILY_ACCOUNT_AUTH_CONSENT_NOT_EXIST = 'PAI_YAPILY_ACCOUNT_AUTH_CONSENT_NOT_EXIST',
  PAI_YAPILY_ACCOUNT_AUTH_CREATE_FAILED = 'PAI_YAPILY_ACCOUNT_AUTH_CREATE_FAILED',
  PAI_YAPILY_ACCOUNT_AUTH_RECONFIRM_FAILED = 'PAI_YAPILY_ACCOUNT_AUTH_RECONFIRM_FAILED',
  PAI_YAPILY_ACCOUNT_AUTH_RECORD_ID_IS_NULL = 'PAI_YAPILY_ACCOUNT_AUTH_RECORD_ID_IS_NULL',
  PAI_YAPILY_ACCOUNT_AUTH_RECORD_NOT_EXIST = 'PAI_YAPILY_ACCOUNT_AUTH_RECORD_NOT_EXIST',
  PAI_YAPILY_ACCOUNT_AWAITING_RE_AUTHORIZATION = 'PAI_YAPILY_ACCOUNT_AWAITING_RE_AUTHORIZATION',
  PAI_YAPILY_BANK_STATEMENT_DUPLICATE = 'PAI_YAPILY_BANK_STATEMENT_DUPLICATE',
  PAI_YEAR_AND_MONTH_ILLEGAL = 'PAI_YEAR_AND_MONTH_ILLEGAL',
  Pai_TARGET_CURRENCY_IS_NULL = 'Pai_TARGET_CURRENCY_IS_NULL',
}
/**
  授权状态
  */
export enum StripeCheckoutStatusEnum {
  COMPLETE = 'COMPLETE',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
}
/**
  同步到会计软件的原因
  */
export enum SyncToAccountingReasonEnum {
  RECON_WITH_STATEMENT_LINE = 'RECON_WITH_STATEMENT_LINE',
  SYNC_BUSINESS_VOUCHER_PAYMENT_RECORD = 'SYNC_BUSINESS_VOUCHER_PAYMENT_RECORD',
  SYNC_DIRECTLY = 'SYNC_DIRECTLY',
  SYNC_FROM_PINVO_IO_TO_ACCOUNTING = 'SYNC_FROM_PINVO_IO_TO_ACCOUNTING',
  SYNC_VOUCHER_ATTACHMENT = 'SYNC_VOUCHER_ATTACHMENT',
}
/**
  同步到会计软件的状态
  */
export enum SyncToAccountingStatusEnum {
  SYNCED = 'SYNCED',
  SYNCING = 'SYNCING',
}
/**
  undefined
  */
export enum undefined {
  RECON_WITH_STATEMENT_LINE = 'RECON_WITH_STATEMENT_LINE',
  SYNC_BUSINESS_VOUCHER_PAYMENT_RECORD = 'SYNC_BUSINESS_VOUCHER_PAYMENT_RECORD',
  SYNC_DIRECTLY = 'SYNC_DIRECTLY',
  SYNC_FROM_PINVO_IO_TO_ACCOUNTING = 'SYNC_FROM_PINVO_IO_TO_ACCOUNTING',
  SYNC_VOUCHER_ATTACHMENT = 'SYNC_VOUCHER_ATTACHMENT',
}
/**
  undefined
  */
export enum undefined {
  SYNCED = 'SYNCED',
  SYNCING = 'SYNCING',
}
/**
  系统参数KEY枚举
  */
export enum SystemParamKeyEnum {
  BOOKKEEPER_EMAIL_WHITE_LIST = 'BOOKKEEPER_EMAIL_WHITE_LIST',
  CLICK_UP_WEBHOOK_CONFIGS = 'CLICK_UP_WEBHOOK_CONFIGS',
  GOOGLE_OAUTH_ACCESS_TOKEN = 'GOOGLE_OAUTH_ACCESS_TOKEN',
  PAL_REPORT_TAXATION_ACCOUNT_NAME_LIST = 'PAL_REPORT_TAXATION_ACCOUNT_NAME_LIST',
  STRIPE_PAYMENT_SETUP_CHECKOUT_SESSION_MESSAGE = 'STRIPE_PAYMENT_SETUP_CHECKOUT_SESSION_MESSAGE',
  STRIPE_PAYMENT_SETUP_PAYMENT_METHODS = 'STRIPE_PAYMENT_SETUP_PAYMENT_METHODS',
  SYNC_FROM_XERO_TO_PINVO_INTERVAL = 'SYNC_FROM_XERO_TO_PINVO_INTERVAL',
  VALID_ORG_IDS = 'VALID_ORG_IDS',
  VOUCHER_AND_BANK_STATEMENT_LINE_SYNC_BETWEEN_ORG = 'VOUCHER_AND_BANK_STATEMENT_LINE_SYNC_BETWEEN_ORG',
}
/**
  表格报表的单元格元数据类型
  */
export enum TableReportCellMetaDataTypeEnum {
  ACCOUNT_ID = 'ACCOUNT_ID',
  CONTACT_ID = 'CONTACT_ID',
  END_DATE = 'END_DATE',
  START_DATE = 'START_DATE',
  UNFOLD = 'UNFOLD',
}
/**
  表格报表的单元格值类型
  */
export enum TableReportCellValueTypeEnum {
  AMOUNT = 'AMOUNT',
  PERCENTAGE = 'PERCENTAGE',
  TEXT = 'TEXT',
}
/**
  税信息的来源：pinvo初始化 或 从会计软件导入
  */
export enum TaxRateSourceEnum {
  QB = 'QB',
  SAGE = 'SAGE',
  XERO = 'XERO',
}
/**
  税率状态
  */
export enum TaxRateStatusEnum {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  DELETED = 'DELETED',
  UNKNOWN = 'UNKNOWN',
}
/**
  试算对账记录明细状态
  */
export enum TrialReconRecordDetailStatusEnum {
  CERTAIN_MATCH = 'CERTAIN_MATCH',
  INIT = 'INIT',
  UNCERTAIN_MATCH = 'UNCERTAIN_MATCH',
}
/**
  试算对账记录状态
  */
export enum TrialReconRecordStatusEnum {
  COMPLETED = 'COMPLETED',
  INIT = 'INIT',
}
/**
  用户角色
  */
export enum UserRoleEnum {
  BOOKKEEPER = 'BOOKKEEPER',
  DIRECTOR = 'DIRECTOR',
  OBSERVER = 'OBSERVER',
}
/**
  凭证子类型
  */
export enum VoucherSubTypeEnum {
  BILL = 'BILL',
  BILL_CREDIT_NOTE = 'BILL_CREDIT_NOTE',
  DIRECT_PAYMENT = 'DIRECT_PAYMENT',
  INTERNAL_TRANSFER = 'INTERNAL_TRANSFER',
  INVOICE = 'INVOICE',
  INVOICE_CREDIT_NOTE = 'INVOICE_CREDIT_NOTE',
  OVERPAYMENT = 'OVERPAYMENT',
  PREPAYMENT = 'PREPAYMENT',
}
